### PR TITLE
fix: unfairWorker may fail due to partial write

### LINKED ISSUE #8: bug: `tinygo/v*.unfairWorker` may fail with `readN != writeN` for some runtime's WASI implementation
## Problem
When running with [water](https://github.com/refraction-networking/water), WATM using `unfairWorker` (including all prebuilt artifacts on the [releases](https://github.com/refraction-networking/watm/releases) page) may fail with error: `YYYY/MM/DD HH:mm:SS worker: unfairWorker: readN != writeN` under high workloadsuch as I/O benchmarking. This effectively jeopardizes all WATMs when workload is high. 

## Analysis
The WebAssembly runtime used by `water` is (a patched fork of) [wazero](https://github.com/refraction-networking/wazero/tags), a pure-Go implementation with WASI support. In `wazero`, when being called upon a TCP socket (underlying type: `*net.TCPConn`), the `wasi_snapshot_preview1::fd_write` is implemented with one single `syscall.Write(fd, buf)` call. 

However, partial write (`nWritten != len(buf)`)  is possible for `syscall.Write()` with no error being returned. 

## Solution
The most compatible way to solve this problem is to treat `fd_write` as equivalent to `syscall.Write()`. In other words, implement the retry logic to call `fd_write` one more time with the bytes left to write (`buf == buf[n:]`) in case not all bytes are written (`n != len(buf)`). 

Alternatively, we might move this logic into the WebAssembly runtime, by rewiring the `fd_write` implementation to use the `(net.Conn).Write` instead. It is important to note that this alternative solution may be more **performance friendly** but less **compatible**, since there is no guarantee for how `fd_write` is implemented in other WebAssembly runtimes and WATER is designed to be easily cross-platform, which assumes maximized runtime compatibility.

### PR DESCRIPTION
**Pull request by gaukas**
Partial write is possible per the implementation of fd_write. This commit adds handler to properly handles the case when partial write occurs.

Fix #8.

### CODE REVIEW

**Comment by gaukas** [comment]
Another commit will be pushed later to backport this fix to `v0`.

**Comment by gaukas** [comment]
Backport completed and verified to be working correctly.

**Comment by gaukas** [comment]
Would you like to give a pass on this PR? @erikziyunchi

**Review by erikchi — APPROVED** [review]
Thanks for the fix, I'll upload the new WATM onto WATER-iOS to test after merging!

**Pull request merged**
