### PR TITLE
new: WATM v1

### PR DESCRIPTION
**Pull request by gaukas**
v1: based on v0, we renamed and redesigned tons of interfaces, introduced new working modes, and fixed potential bugs.

### CODE REVIEW

**Comment by gaukas** [comment]
Weird. Theoretically this shouldn't happen with `cpu` package properly replaced.

**Comment by gaukas** [comment]
I see, we are (indirectly) using v0.19.0, but the replace directive replaces only v0.16.0.

**Review by erikchi — APPROVED** [review]
LGTM! Thanks for adding it! I think next time maybe we can put the dependencies change in one commit, and code changes in others?

**Comment by gaukas** [comment]
> ... maybe we can put the dependencies change in one commit, and code changes in others?

That's the ideal case. For this repo, since the build relies on `replace` directive and the old `go.mod` will not build for the new content in `v1` directory, we have to make all changes before any local test would pass.

**Pull request merged**
